package top.m24h.android

import android.content.Context
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.BaseAdapter
import androidx.appcompat.app.AppCompatActivity
import androidx.databinding.DataBindingUtil
import androidx.databinding.ViewDataBinding

/**
 * data binding for Activity, <B> is automatically generated by Android Studio
 */
open class DataBindActivity<B:ViewDataBinding> (val layoutId:Int)
    : AppCompatActivity() {
    // data binding
    lateinit var binding:B

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView<B>(this, layoutId)
    }
}

/**
 * data binding for ListView
 * about `itemSetNameJava`, for &lt;variable name="abc" type="V" /&gt;, it should be `setAbc`
 */
open class DataBindListViewAdapter<V, T:ViewDataBinding, L:List<V>> (
    val context: Context,
    val itemLayoutID: Int,
    val itemSetNameJava: String,
    val data:L
) : BaseAdapter() {
    @Suppress("unused")
    override fun getCount(): Int {
        return data.count()
    }
    @Suppress("unused")
    override fun getItem(position: Int): Any? {
        return data[position]
    }
    @Suppress("unused")
    override fun getItemId(position: Int): Long {
        return position.toLong()
    }
    @Suppress("unused")
    override fun getView(position: Int, view: View?, parent: ViewGroup?): View? {
        val binding: T = view?.let { 
            DataBindingUtil.getBinding(it) 
            } ?: DataBindingUtil.inflate(
                LayoutInflater.from(context), itemLayoutID, parent, false
            )
        data[position]?.let {
            binding.javaClass.getDeclaredMethod(
                itemSetNameJava, it::class.java
            ).invoke(binding, it)
        }
        return binding.root
    }
}